//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masterial
    {
        public string PurchaseID { get; set; }
        public int No { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Color_Principle { get; set; }
        public string Grain { get; set; }
        public int Thickness { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<int> Dimention_Weight { get; set; }
        public string Note { get; set; }
    }
}
